ctx.rule(u'START', u'{SQL_STMT_LIST}')
ctx.rule(u'SQL_STMT_LIST', u'{SQL_STMT}{AUX_1}{SCOL_T}{NEWLINE_T}')
ctx.rule(u'AUX_1', u'')
ctx.rule(u'AUX_1', u'{GROUP_0}{AUX_1}')
ctx.rule(u'GROUP_0', u'{SCOL_T}{NEWLINE_T}{SQL_STMT}')
ctx.rule(u'SQL_STMT', u'{AUX_2}{GROUP_3}')
ctx.rule(u'AUX_2', u'')
ctx.rule(u'AUX_2', u'{GROUP_1}')
ctx.rule(u'GROUP_1', u'{EXPLAIN_T}{AUX_3}')
ctx.rule(u'AUX_3', u'')
ctx.rule(u'AUX_3', u'{GROUP_2}')
ctx.rule(u'GROUP_2', u'{QUERY_T}{PLAN_T}')
ctx.rule(u'GROUP_3', u'{ALTER_TABLE_STMT}')
ctx.rule(u'GROUP_3', u'{ANALYZE_STMT}')
ctx.rule(u'GROUP_3', u'{ATTACH_STMT}')
ctx.rule(u'GROUP_3', u'{BEGIN_STMT}')
ctx.rule(u'GROUP_3', u'{COMMIT_STMT}')
ctx.rule(u'GROUP_3', u'{CREATE_INDEX_STMT}')
ctx.rule(u'GROUP_3', u'{CREATE_TABLE_STMT}')
ctx.rule(u'GROUP_3', u'{CREATE_TRIGGER_STMT}')
ctx.rule(u'GROUP_3', u'{CREATE_VIEW_STMT}')
ctx.rule(u'GROUP_3', u'{DELETE_STMT}')
ctx.rule(u'GROUP_3', u'{DELETE_STMT_LIMITED}')
ctx.rule(u'GROUP_3', u'{DETACH_STMT}')
ctx.rule(u'GROUP_3', u'{DROP_INDEX_STMT}')
ctx.rule(u'GROUP_3', u'{DROP_TABLE_STMT}')
ctx.rule(u'GROUP_3', u'{DROP_TRIGGER_STMT}')
ctx.rule(u'GROUP_3', u'{DROP_VIEW_STMT}')
ctx.rule(u'GROUP_3', u'{INSERT_STMT}')
ctx.rule(u'GROUP_3', u'{PRAGMA_STMT}')
ctx.rule(u'GROUP_3', u'{REINDEX_STMT}')
ctx.rule(u'GROUP_3', u'{RELEASE_STMT}')
ctx.rule(u'GROUP_3', u'{ROLLBACK_STMT}')
ctx.rule(u'GROUP_3', u'{SAVEPOINT_STMT}')
ctx.rule(u'GROUP_3', u'{SELECT_STMT}')
ctx.rule(u'GROUP_3', u'{UPDATE_STMT}')
ctx.rule(u'GROUP_3', u'{UPDATE_STMT_LIMITED}')
ctx.rule(u'GROUP_3', u'{VACUUM_STMT}')
ctx.rule(u'ALTER_TABLE_STMT', u'{ALTER_T}{TABLE_T}{AUX_4}{TABLE_NAME}{GROUP_5}')
ctx.rule(u'AUX_4', u'')
ctx.rule(u'AUX_4', u'{GROUP_4}')
ctx.rule(u'GROUP_4', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_5', u'{RENAME_T}{TO_T}{NEW_TABLE_NAME}')
ctx.rule(u'GROUP_5', u'{RENAME_T}{AUX_5}{COLUMN_NAME}{TO_T}{COLUMN_NAME}')
ctx.rule(u'AUX_5', u'')
ctx.rule(u'AUX_5', u'{COLUMN_T}')
ctx.rule(u'GROUP_5', u'{ADD_T}{AUX_6}{COLUMN_DEF}')
ctx.rule(u'AUX_6', u'')
ctx.rule(u'AUX_6', u'{COLUMN_T}')
ctx.rule(u'GROUP_5', u'{DROP_T}{AUX_7}{COLUMN_NAME}')
ctx.rule(u'AUX_7', u'')
ctx.rule(u'AUX_7', u'{COLUMN_T}')
ctx.rule(u'ANALYZE_STMT', u'{ANALYZE_T}{GROUP_6}')
ctx.rule(u'GROUP_6', u'{SCHEMA_NAME}')
ctx.rule(u'GROUP_6', u'{INDEX_OR_TABLE_NAME}')
ctx.rule(u'GROUP_6', u'{SCHEMA_NAME}{DOT_T}{INDEX_OR_TABLE_NAME}')
ctx.rule(u'ATTACH_STMT', u'{ATTACH_T}{AUX_8}{EXPR}{AS_T}{SCHEMA_NAME}')
ctx.rule(u'AUX_8', u'')
ctx.rule(u'AUX_8', u'{DATABASE_T}')
ctx.rule(u'BEGIN_STMT', u'{BEGIN_T}{AUX_9}{AUX_10}')
ctx.rule(u'AUX_9', u'')
ctx.rule(u'AUX_9', u'{GROUP_7}')
ctx.rule(u'AUX_10', u'')
ctx.rule(u'AUX_10', u'{TRANSACTION_T}')
ctx.rule(u'GROUP_7', u'{DEFERRED_T}')
ctx.rule(u'GROUP_7', u'{IMMEDIATE_T}')
ctx.rule(u'GROUP_7', u'{EXCLUSIVE_T}')
ctx.rule(u'COMMIT_STMT', u'{GROUP_8}{AUX_11}')
ctx.rule(u'AUX_11', u'')
ctx.rule(u'AUX_11', u'{TRANSACTION_T}')
ctx.rule(u'GROUP_8', u'{COMMIT_T}')
ctx.rule(u'GROUP_8', u'{END_T}')
ctx.rule(u'ROLLBACK_STMT', u'{ROLLBACK_T}{AUX_12}{AUX_13}')
ctx.rule(u'AUX_12', u'')
ctx.rule(u'AUX_12', u'{TRANSACTION_T}')
ctx.rule(u'AUX_13', u'')
ctx.rule(u'AUX_13', u'{GROUP_9}')
ctx.rule(u'GROUP_9', u'{TO_T}{AUX_14}{SAVEPOINT_NAME}')
ctx.rule(u'AUX_14', u'')
ctx.rule(u'AUX_14', u'{SAVEPOINT_T}')
ctx.rule(u'SAVEPOINT_STMT', u'{SAVEPOINT_T}{SAVEPOINT_NAME}')
ctx.rule(u'RELEASE_STMT', u'{RELEASE_T}{AUX_15}{SAVEPOINT_NAME}')
ctx.rule(u'AUX_15', u'')
ctx.rule(u'AUX_15', u'{SAVEPOINT_T}')
ctx.rule(u'CREATE_INDEX_STMT', u'{CREATE_T}{AUX_16}{INDEX_T}{AUX_17}{AUX_18}{INDEX_NAME}{ON_T}{TABLE_NAME}{OPEN_PAR_T}{INDEXED_COLUMN}{AUX_19}{CLOSE_PAR_T}{AUX_20}')
ctx.rule(u'AUX_16', u'')
ctx.rule(u'AUX_16', u'{UNIQUE_T}')
ctx.rule(u'AUX_17', u'')
ctx.rule(u'AUX_17', u'{GROUP_10}')
ctx.rule(u'AUX_18', u'')
ctx.rule(u'AUX_18', u'{GROUP_11}')
ctx.rule(u'AUX_19', u'')
ctx.rule(u'AUX_19', u'{GROUP_12}{AUX_19}')
ctx.rule(u'AUX_20', u'')
ctx.rule(u'AUX_20', u'{GROUP_13}')
ctx.rule(u'GROUP_10', u'{IF_T}{NOT_T}{EXISTS_T}')
ctx.rule(u'GROUP_11', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_12', u'{COMMA_T}{INDEXED_COLUMN}')
ctx.rule(u'GROUP_13', u'{WHERE_T}{EXPR}')
ctx.rule(u'INDEXED_COLUMN', u'{GROUP_14}{AUX_21}{AUX_22}')
ctx.rule(u'AUX_21', u'')
ctx.rule(u'AUX_21', u'{GROUP_15}')
ctx.rule(u'AUX_22', u'')
ctx.rule(u'AUX_22', u'{GROUP_16}')
ctx.rule(u'GROUP_14', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_14', u'{EXPR}')
ctx.rule(u'GROUP_15', u'{COLLATE_T}{COLLATION_NAME}')
ctx.rule(u'GROUP_16', u'{ASC_T}')
ctx.rule(u'GROUP_16', u'{DESC_T}')
ctx.rule(u'CREATE_TABLE_STMT', u'{CREATE_T}{AUX_23}{TABLE_T}{AUX_24}{AUX_25}{TABLE_NAME}{GROUP_20}')
ctx.rule(u'AUX_23', u'')
ctx.rule(u'AUX_23', u'{GROUP_17}')
ctx.rule(u'AUX_24', u'')
ctx.rule(u'AUX_24', u'{GROUP_18}')
ctx.rule(u'AUX_25', u'')
ctx.rule(u'AUX_25', u'{GROUP_19}')
ctx.rule(u'GROUP_17', u'{TEMP_T}')
ctx.rule(u'GROUP_17', u'{TEMPORARY_T}')
ctx.rule(u'GROUP_18', u'{IF_T}{NOT_T}{EXISTS_T}')
ctx.rule(u'GROUP_19', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_20', u'{AS_T}{SELECT_STMT}')
ctx.rule(u'GROUP_20', u'{OPEN_PAR_T}{COLUMN_DEF}{AUX_26}{AUX_27}{CLOSE_PAR_T}{AUX_28}')
ctx.rule(u'AUX_26', u'')
ctx.rule(u'AUX_26', u'{GROUP_21}{AUX_26}')
ctx.rule(u'AUX_27', u'')
ctx.rule(u'AUX_27', u'{GROUP_22}')
ctx.rule(u'AUX_28', u'')
ctx.rule(u'AUX_28', u'{TABLE_OPTIONS}')
ctx.rule(u'GROUP_21', u'{COMMA_T}{COLUMN_DEF}')
ctx.rule(u'GROUP_22', u'{TABLE_CONSTRAINT}{AUX_29}')
ctx.rule(u'AUX_29', u'')
ctx.rule(u'AUX_29', u'{GROUP_23}{AUX_29}')
ctx.rule(u'GROUP_23', u'{COMMA_T}{TABLE_CONSTRAINT}')
ctx.rule(u'TABLE_OPTIONS', u'{GROUP_24}{AUX_30}')
ctx.rule(u'AUX_30', u'')
ctx.rule(u'AUX_30', u'{GROUP_25}{AUX_30}')
ctx.rule(u'GROUP_24', u'{WITHOUT_T}{ROWID_T}')
ctx.rule(u'GROUP_24', u'{STRICT_T}')
ctx.rule(u'GROUP_25', u'{COMMA_T}{GROUP_26}')
ctx.rule(u'GROUP_26', u'{WITHOUT_T}{ROWID_T}')
ctx.rule(u'GROUP_26', u'{STRICT_T}')
ctx.rule(u'COLUMN_DEF', u'{COLUMN_NAME}{AUX_31}{AUX_32}')
ctx.rule(u'AUX_31', u'')
ctx.rule(u'AUX_31', u'{TYPE_NAME}')
ctx.rule(u'AUX_32', u'')
ctx.rule(u'AUX_32', u'{COLUMN_CONSTRAINT}{AUX_32}')
ctx.rule(u'TYPE_NAME', u'{GROUP_27}{AUX_33}')
ctx.rule(u'AUX_33', u'')
ctx.rule(u'AUX_33', u'{GROUP_28}')
ctx.rule(u'GROUP_27', u'{TYPE_BASE_NAME_T}')
ctx.rule(u'GROUP_27', u'{NULL_T}')
ctx.rule(u'GROUP_28', u'{OPEN_PAR_T}{SIGNED_NUMBER}{CLOSE_PAR_T}')
ctx.rule(u'GROUP_28', u'{OPEN_PAR_T}{SIGNED_NUMBER}{COMMA_T}{SIGNED_NUMBER}{CLOSE_PAR_T}')
ctx.rule(u'COLUMN_CONSTRAINT', u'{AUX_34}{GROUP_30}')
ctx.rule(u'AUX_34', u'')
ctx.rule(u'AUX_34', u'{GROUP_29}')
ctx.rule(u'GROUP_29', u'{CONSTRAINT_T}{CONSTRAINT_NAME_T}')
ctx.rule(u'GROUP_30', u'{GROUP_31}')
ctx.rule(u'GROUP_30', u'{NOT_T}{NULL_T}{CONFLICT_CLAUSE}')
ctx.rule(u'GROUP_30', u'{UNIQUE_T}{CONFLICT_CLAUSE}')
ctx.rule(u'GROUP_30', u'{CHECK_T}{OPEN_PAR_T}{EXPR}{CLOSE_PAR_T}')
ctx.rule(u'GROUP_30', u'{DEFAULT_T}{GROUP_33}')
ctx.rule(u'GROUP_30', u'{COLLATE_T}{COLLATION_NAME}')
ctx.rule(u'GROUP_30', u'{FOREIGN_KEY_CLAUSE}')
ctx.rule(u'GROUP_30', u'{AUX_35}{AS_T}{OPEN_PAR_T}{EXPR}{CLOSE_PAR_T}{AUX_36}')
ctx.rule(u'AUX_35', u'')
ctx.rule(u'AUX_35', u'{GROUP_34}')
ctx.rule(u'AUX_36', u'')
ctx.rule(u'AUX_36', u'{GROUP_35}')
ctx.rule(u'GROUP_31', u'{PRIMARY_T}{KEY_T}{AUX_37}{CONFLICT_CLAUSE}{AUX_38}')
ctx.rule(u'AUX_37', u'')
ctx.rule(u'AUX_37', u'{GROUP_32}')
ctx.rule(u'AUX_38', u'')
ctx.rule(u'AUX_38', u'{AUTOINCREMENT_T}')
ctx.rule(u'GROUP_32', u'{ASC_T}')
ctx.rule(u'GROUP_32', u'{DESC_T}')
ctx.rule(u'GROUP_33', u'{OPEN_PAR_T}{EXPR}{CLOSE_PAR_T}')
ctx.rule(u'GROUP_33', u'{LITERAL_VALUE}')
ctx.rule(u'GROUP_33', u'{SIGNED_NUMBER}')
ctx.rule(u'GROUP_34', u'{GENERATED_T}{ALWAYS_T}')
ctx.rule(u'GROUP_35', u'{STORED_T}')
ctx.rule(u'GROUP_35', u'{VIRTUAL_T}')
ctx.rule(u'SIGNED_NUMBER', u'{AUX_39}{NUMERIC_LITERAL_T}')
ctx.rule(u'AUX_39', u'')
ctx.rule(u'AUX_39', u'{GROUP_36}')
ctx.rule(u'GROUP_36', u'{PLUS_T}')
ctx.rule(u'GROUP_36', u'{MINUS_T}')
ctx.rule(u'TABLE_CONSTRAINT', u'{AUX_40}{GROUP_38}')
ctx.rule(u'AUX_40', u'')
ctx.rule(u'AUX_40', u'{GROUP_37}')
ctx.rule(u'GROUP_37', u'{CONSTRAINT_T}{CONSTRAINT_NAME_T}')
ctx.rule(u'GROUP_38', u'{GROUP_39}{OPEN_PAR_T}{INDEXED_COLUMN}{AUX_41}{CLOSE_PAR_T}{CONFLICT_CLAUSE}')
ctx.rule(u'AUX_41', u'')
ctx.rule(u'AUX_41', u'{GROUP_40}{AUX_41}')
ctx.rule(u'GROUP_38', u'{CHECK_T}{OPEN_PAR_T}{EXPR}{CLOSE_PAR_T}')
ctx.rule(u'GROUP_38', u'{FOREIGN_T}{KEY_T}{OPEN_PAR_T}{COLUMN_NAME}{AUX_42}{CLOSE_PAR_T}{FOREIGN_KEY_CLAUSE}')
ctx.rule(u'AUX_42', u'')
ctx.rule(u'AUX_42', u'{GROUP_41}{AUX_42}')
ctx.rule(u'GROUP_39', u'{PRIMARY_T}{KEY_T}')
ctx.rule(u'GROUP_39', u'{UNIQUE_T}')
ctx.rule(u'GROUP_40', u'{COMMA_T}{INDEXED_COLUMN}')
ctx.rule(u'GROUP_41', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'FOREIGN_KEY_CLAUSE', u'{REFERENCES_T}{FOREIGN_TABLE}{AUX_43}{AUX_44}{AUX_45}')
ctx.rule(u'AUX_43', u'')
ctx.rule(u'AUX_43', u'{GROUP_42}')
ctx.rule(u'AUX_44', u'')
ctx.rule(u'AUX_44', u'{GROUP_44}{AUX_44}')
ctx.rule(u'AUX_45', u'')
ctx.rule(u'AUX_45', u'{GROUP_48}')
ctx.rule(u'GROUP_42', u'{OPEN_PAR_T}{COLUMN_NAME}{AUX_46}{CLOSE_PAR_T}')
ctx.rule(u'AUX_46', u'')
ctx.rule(u'AUX_46', u'{GROUP_43}{AUX_46}')
ctx.rule(u'GROUP_43', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'GROUP_44', u'{ON_T}{GROUP_45}{GROUP_46}')
ctx.rule(u'GROUP_45', u'{DELETE_T}')
ctx.rule(u'GROUP_45', u'{UPDATE_T}')
ctx.rule(u'GROUP_46', u'{SET_T}{GROUP_47}')
ctx.rule(u'GROUP_46', u'{CASCADE_T}')
ctx.rule(u'GROUP_46', u'{RESTRICT_T}')
ctx.rule(u'GROUP_46', u'{NO_T}{ACTION_T}')
ctx.rule(u'GROUP_47', u'{NULL_T}')
ctx.rule(u'GROUP_47', u'{DEFAULT_T}')
ctx.rule(u'GROUP_48', u'{AUX_47}{DEFERRABLE_T}{AUX_48}')
ctx.rule(u'AUX_47', u'')
ctx.rule(u'AUX_47', u'{NOT_T}')
ctx.rule(u'AUX_48', u'')
ctx.rule(u'AUX_48', u'{GROUP_49}')
ctx.rule(u'GROUP_49', u'{INITIALLY_T}{GROUP_50}')
ctx.rule(u'GROUP_50', u'{DEFERRED_T}')
ctx.rule(u'GROUP_50', u'{IMMEDIATE_T}')
ctx.rule(u'CONFLICT_CLAUSE', u'{AUX_49}')
ctx.rule(u'AUX_49', u'')
ctx.rule(u'AUX_49', u'{GROUP_51}')
ctx.rule(u'GROUP_51', u'{ON_T}{CONFLICT_T}{GROUP_52}')
ctx.rule(u'GROUP_52', u'{ROLLBACK_T}')
ctx.rule(u'GROUP_52', u'{ABORT_T}')
ctx.rule(u'GROUP_52', u'{FAIL_T}')
ctx.rule(u'GROUP_52', u'{IGNORE_T}')
ctx.rule(u'GROUP_52', u'{REPLACE_T}')
ctx.rule(u'CREATE_TRIGGER_STMT', u'{CREATE_T}{AUX_50}{TRIGGER_T}{AUX_51}{AUX_52}{TRIGGER_NAME}{AUX_53}{GROUP_57}{ON_T}{TABLE_NAME}{AUX_54}{AUX_55}{BEGIN_T}{AUX_56}{END_T}')
ctx.rule(u'AUX_50', u'')
ctx.rule(u'AUX_50', u'{GROUP_53}')
ctx.rule(u'AUX_51', u'')
ctx.rule(u'AUX_51', u'{GROUP_54}')
ctx.rule(u'AUX_52', u'')
ctx.rule(u'AUX_52', u'{GROUP_55}')
ctx.rule(u'AUX_53', u'')
ctx.rule(u'AUX_53', u'{GROUP_56}')
ctx.rule(u'AUX_54', u'')
ctx.rule(u'AUX_54', u'{GROUP_61}')
ctx.rule(u'AUX_55', u'')
ctx.rule(u'AUX_55', u'{GROUP_62}')
ctx.rule(u'AUX_56', u'{GROUP_63}')
ctx.rule(u'AUX_56', u'{GROUP_63}{AUX_56}')
ctx.rule(u'GROUP_53', u'{TEMP_T}')
ctx.rule(u'GROUP_53', u'{TEMPORARY_T}')
ctx.rule(u'GROUP_54', u'{IF_T}{NOT_T}{EXISTS_T}')
ctx.rule(u'GROUP_55', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_56', u'{BEFORE_T}')
ctx.rule(u'GROUP_56', u'{AFTER_T}')
ctx.rule(u'GROUP_56', u'{INSTEAD_T}{OF_T}')
ctx.rule(u'GROUP_57', u'{DELETE_T}')
ctx.rule(u'GROUP_57', u'{INSERT_T}')
ctx.rule(u'GROUP_57', u'{GROUP_58}')
ctx.rule(u'GROUP_58', u'{UPDATE_T}{AUX_57}')
ctx.rule(u'AUX_57', u'')
ctx.rule(u'AUX_57', u'{GROUP_59}')
ctx.rule(u'GROUP_59', u'{OF_T}{COLUMN_NAME}{AUX_58}')
ctx.rule(u'AUX_58', u'')
ctx.rule(u'AUX_58', u'{GROUP_60}{AUX_58}')
ctx.rule(u'GROUP_60', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'GROUP_61', u'{FOR_T}{EACH_T}{ROW_T}')
ctx.rule(u'GROUP_62', u'{WHEN_T}{EXPR}')
ctx.rule(u'GROUP_63', u'{GROUP_64}{SCOL_T}')
ctx.rule(u'GROUP_64', u'{UPDATE_STMT}')
ctx.rule(u'GROUP_64', u'{INSERT_STMT}')
ctx.rule(u'GROUP_64', u'{DELETE_STMT}')
ctx.rule(u'GROUP_64', u'{SELECT_STMT}')
ctx.rule(u'CREATE_VIEW_STMT', u'{CREATE_T}{AUX_59}{VIEW_T}{AUX_60}{AUX_61}{VIEW_NAME}{AUX_62}{AS_T}{SELECT_STMT}')
ctx.rule(u'AUX_59', u'')
ctx.rule(u'AUX_59', u'{GROUP_65}')
ctx.rule(u'AUX_60', u'')
ctx.rule(u'AUX_60', u'{GROUP_66}')
ctx.rule(u'AUX_61', u'')
ctx.rule(u'AUX_61', u'{GROUP_67}')
ctx.rule(u'AUX_62', u'')
ctx.rule(u'AUX_62', u'{GROUP_68}')
ctx.rule(u'GROUP_65', u'{TEMP_T}')
ctx.rule(u'GROUP_65', u'{TEMPORARY_T}')
ctx.rule(u'GROUP_66', u'{IF_T}{NOT_T}{EXISTS_T}')
ctx.rule(u'GROUP_67', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_68', u'{OPEN_PAR_T}{COLUMN_NAME}{AUX_63}{CLOSE_PAR_T}')
ctx.rule(u'AUX_63', u'')
ctx.rule(u'AUX_63', u'{GROUP_69}{AUX_63}')
ctx.rule(u'GROUP_69', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'COMMON_TABLE_EXPRESSION', u'{TABLE_NAME}{AUX_64}{AS_T}{AUX_65}{OPEN_PAR_T}{SELECT_STMT}{CLOSE_PAR_T}')
ctx.rule(u'AUX_64', u'')
ctx.rule(u'AUX_64', u'{GROUP_70}')
ctx.rule(u'AUX_65', u'')
ctx.rule(u'AUX_65', u'{GROUP_72}')
ctx.rule(u'GROUP_70', u'{OPEN_PAR_T}{COLUMN_NAME}{AUX_66}{CLOSE_PAR_T}')
ctx.rule(u'AUX_66', u'')
ctx.rule(u'AUX_66', u'{GROUP_71}{AUX_66}')
ctx.rule(u'GROUP_71', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'GROUP_72', u'{AUX_67}{MATERIALIZED_T}')
ctx.rule(u'AUX_67', u'')
ctx.rule(u'AUX_67', u'{NOT_T}')
ctx.rule(u'DELETE_STMT', u'{AUX_68}{DELETE_T}{FROM_T}{QUALIFIED_TABLE_NAME}{AUX_69}{AUX_70}')
ctx.rule(u'AUX_68', u'')
ctx.rule(u'AUX_68', u'{GROUP_73}')
ctx.rule(u'AUX_69', u'')
ctx.rule(u'AUX_69', u'{GROUP_75}')
ctx.rule(u'AUX_70', u'')
ctx.rule(u'AUX_70', u'{RETURNING_CLAUSE}')
ctx.rule(u'GROUP_73', u'{WITH_T}{AUX_71}{COMMON_TABLE_EXPRESSION}{AUX_72}')
ctx.rule(u'AUX_71', u'')
ctx.rule(u'AUX_71', u'{RECURSIVE_T}')
ctx.rule(u'AUX_72', u'')
ctx.rule(u'AUX_72', u'{GROUP_74}{AUX_72}')
ctx.rule(u'GROUP_74', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_75', u'{WHERE_T}{EXPR}')
ctx.rule(u'DELETE_STMT_LIMITED', u'{AUX_73}{DELETE_T}{FROM_T}{QUALIFIED_TABLE_NAME}{AUX_74}{AUX_75}{AUX_76}')
ctx.rule(u'AUX_73', u'')
ctx.rule(u'AUX_73', u'{GROUP_76}')
ctx.rule(u'AUX_74', u'')
ctx.rule(u'AUX_74', u'{GROUP_78}')
ctx.rule(u'AUX_75', u'')
ctx.rule(u'AUX_75', u'{RETURNING_CLAUSE}')
ctx.rule(u'AUX_76', u'')
ctx.rule(u'AUX_76', u'{GROUP_79}')
ctx.rule(u'GROUP_76', u'{WITH_T}{AUX_77}{COMMON_TABLE_EXPRESSION}{AUX_78}')
ctx.rule(u'AUX_77', u'')
ctx.rule(u'AUX_77', u'{RECURSIVE_T}')
ctx.rule(u'AUX_78', u'')
ctx.rule(u'AUX_78', u'{GROUP_77}{AUX_78}')
ctx.rule(u'GROUP_77', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_78', u'{WHERE_T}{EXPR}')
ctx.rule(u'GROUP_79', u'{ORDER_T}{BY_T}{ORDERING_TERM}{AUX_79}{LIMIT_T}{EXPR}{AUX_80}')
ctx.rule(u'AUX_79', u'')
ctx.rule(u'AUX_79', u'{GROUP_80}{AUX_79}')
ctx.rule(u'AUX_80', u'')
ctx.rule(u'AUX_80', u'{GROUP_81}')
ctx.rule(u'GROUP_80', u'{COMMA_T}{ORDERING_TERM}')
ctx.rule(u'GROUP_81', u'{OFFSET_T}{EXPR}')
ctx.rule(u'GROUP_81', u'{COMMA_T}{EXPR}')
ctx.rule(u'DETACH_STMT', u'{DETACH_T}{AUX_81}{SCHEMA_NAME}')
ctx.rule(u'AUX_81', u'')
ctx.rule(u'AUX_81', u'{DATABASE_T}')
ctx.rule(u'DROP_INDEX_STMT', u'{DROP_T}{INDEX_T}{AUX_82}{AUX_83}{INDEX_NAME}')
ctx.rule(u'AUX_82', u'')
ctx.rule(u'AUX_82', u'{GROUP_82}')
ctx.rule(u'AUX_83', u'')
ctx.rule(u'AUX_83', u'{GROUP_83}')
ctx.rule(u'GROUP_82', u'{IF_T}{EXISTS_T}')
ctx.rule(u'GROUP_83', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'DROP_TABLE_STMT', u'{DROP_T}{TABLE_T}{AUX_84}{AUX_85}{TABLE_NAME}')
ctx.rule(u'AUX_84', u'')
ctx.rule(u'AUX_84', u'{GROUP_84}')
ctx.rule(u'AUX_85', u'')
ctx.rule(u'AUX_85', u'{GROUP_85}')
ctx.rule(u'GROUP_84', u'{IF_T}{EXISTS_T}')
ctx.rule(u'GROUP_85', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'DROP_TRIGGER_STMT', u'{DROP_T}{TRIGGER_T}{AUX_86}{AUX_87}{TRIGGER_NAME}')
ctx.rule(u'AUX_86', u'')
ctx.rule(u'AUX_86', u'{GROUP_86}')
ctx.rule(u'AUX_87', u'')
ctx.rule(u'AUX_87', u'{GROUP_87}')
ctx.rule(u'GROUP_86', u'{IF_T}{EXISTS_T}')
ctx.rule(u'GROUP_87', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'DROP_VIEW_STMT', u'{DROP_T}{VIEW_T}{AUX_88}{AUX_89}{VIEW_NAME}')
ctx.rule(u'AUX_88', u'')
ctx.rule(u'AUX_88', u'{GROUP_88}')
ctx.rule(u'AUX_89', u'')
ctx.rule(u'AUX_89', u'{GROUP_89}')
ctx.rule(u'GROUP_88', u'{IF_T}{EXISTS_T}')
ctx.rule(u'GROUP_89', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'EXPR', u'{LITERAL_VALUE}')
ctx.rule(u'EXPR', u'{AUX_90}{COLUMN_NAME}')
ctx.rule(u'AUX_90', u'')
ctx.rule(u'AUX_90', u'{GROUP_90}')
ctx.rule(u'EXPR', u'{UNARY_OPERATOR}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_92}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_93}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_94}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_95}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_96}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_97}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{AND_T}{EXPR}')
ctx.rule(u'EXPR', u'{EXPR}{OR_T}{EXPR}')
ctx.rule(u'EXPR', u'{FUNCTION}')
ctx.rule(u'EXPR', u'{OPEN_PAR_T}{EXPR}{AUX_91}{CLOSE_PAR_T}')
ctx.rule(u'AUX_91', u'')
ctx.rule(u'AUX_91', u'{GROUP_98}{AUX_91}')
ctx.rule(u'EXPR', u'{CAST_T}{OPEN_PAR_T}{EXPR}{AS_T}{TYPE_NAME}{CLOSE_PAR_T}')
ctx.rule(u'EXPR', u'{EXPR}{COLLATE_T}{COLLATION_NAME}')
ctx.rule(u'EXPR', u'{EXPR}{AUX_92}{GROUP_99}{EXPR}{AUX_93}')
ctx.rule(u'AUX_92', u'')
ctx.rule(u'AUX_92', u'{NOT_T}')
ctx.rule(u'AUX_93', u'')
ctx.rule(u'AUX_93', u'{GROUP_100}')
ctx.rule(u'EXPR', u'{EXPR}{GROUP_101}')
ctx.rule(u'EXPR', u'{EXPR}{IS_T}{AUX_94}{EXPR}')
ctx.rule(u'AUX_94', u'')
ctx.rule(u'AUX_94', u'{NOT_T}')
ctx.rule(u'EXPR', u'{EXPR}{AUX_95}{BETWEEN_T}{EXPR}{AND_T}{EXPR}')
ctx.rule(u'AUX_95', u'')
ctx.rule(u'AUX_95', u'{NOT_T}')
ctx.rule(u'EXPR', u'{EXPR}{AUX_96}{IN_T}{GROUP_102}')
ctx.rule(u'AUX_96', u'')
ctx.rule(u'AUX_96', u'{NOT_T}')
ctx.rule(u'EXPR', u'{AUX_97}{OPEN_PAR_T}{SELECT_STMT}{CLOSE_PAR_T}')
ctx.rule(u'AUX_97', u'')
ctx.rule(u'AUX_97', u'{GROUP_106}')
ctx.rule(u'EXPR', u'{CASE_T}{AUX_98}{AUX_99}{AUX_100}{END_T}')
ctx.rule(u'AUX_98', u'')
ctx.rule(u'AUX_98', u'{EXPR}')
ctx.rule(u'AUX_99', u'{GROUP_108}')
ctx.rule(u'AUX_99', u'{GROUP_108}{AUX_99}')
ctx.rule(u'AUX_100', u'')
ctx.rule(u'AUX_100', u'{GROUP_109}')
ctx.rule(u'EXPR', u'{RAISE_FUNCTION}')
ctx.rule(u'GROUP_90', u'{AUX_101}{TABLE_NAME}{DOT_T}')
ctx.rule(u'AUX_101', u'')
ctx.rule(u'AUX_101', u'{GROUP_91}')
ctx.rule(u'GROUP_91', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_92', u'{PIPE2_}')
ctx.rule(u'GROUP_92', u'{R_ARR1_}')
ctx.rule(u'GROUP_92', u'{R_ARR2_}')
ctx.rule(u'GROUP_93', u'{STAR_T}')
ctx.rule(u'GROUP_93', u'{DIV_T}')
ctx.rule(u'GROUP_93', u'{MOD_T}')
ctx.rule(u'GROUP_94', u'{PLUS_T}')
ctx.rule(u'GROUP_94', u'{MINUS_T}')
ctx.rule(u'GROUP_95', u'{LT2_}')
ctx.rule(u'GROUP_95', u'{GT2_}')
ctx.rule(u'GROUP_95', u'{AMP_T}')
ctx.rule(u'GROUP_95', u'{PIPE_T}')
ctx.rule(u'GROUP_96', u'{LT_T}')
ctx.rule(u'GROUP_96', u'{LT_EQ_T}')
ctx.rule(u'GROUP_96', u'{GT_T}')
ctx.rule(u'GROUP_96', u'{GT_EQ_T}')
ctx.rule(u'GROUP_97', u'{ASSIGN_T}')
ctx.rule(u'GROUP_97', u'{EQ_T}')
ctx.rule(u'GROUP_97', u'{NOT_EQ1_}')
ctx.rule(u'GROUP_97', u'{NOT_EQ2_}')
ctx.rule(u'GROUP_97', u'{IS_T}')
ctx.rule(u'GROUP_97', u'{IS_T}{NOT_T}')
ctx.rule(u'GROUP_97', u'{IN_T}')
ctx.rule(u'GROUP_97', u'{LIKE_T}')
ctx.rule(u'GROUP_97', u'{GLOB_T}')
ctx.rule(u'GROUP_97', u'{MATCH_T}')
ctx.rule(u'GROUP_97', u'{REGEXP_T}')
ctx.rule(u'GROUP_98', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_99', u'{LIKE_T}')
ctx.rule(u'GROUP_99', u'{GLOB_T}')
ctx.rule(u'GROUP_99', u'{REGEXP_T}')
ctx.rule(u'GROUP_99', u'{MATCH_T}')
ctx.rule(u'GROUP_100', u'{ESCAPE_T}{EXPR}')
ctx.rule(u'GROUP_101', u'{ISNULL_T}')
ctx.rule(u'GROUP_101', u'{NOTNULL_T}')
ctx.rule(u'GROUP_101', u'{NOT_T}{NULL_T}')
ctx.rule(u'GROUP_102', u'{OPEN_PAR_T}{AUX_102}{CLOSE_PAR_T}')
ctx.rule(u'AUX_102', u'')
ctx.rule(u'AUX_102', u'{GROUP_103}')
ctx.rule(u'GROUP_102', u'{AUX_103}{TABLE_NAME}')
ctx.rule(u'AUX_103', u'')
ctx.rule(u'AUX_103', u'{GROUP_105}')
ctx.rule(u'GROUP_103', u'{SELECT_STMT}')
ctx.rule(u'GROUP_103', u'{EXPR}{AUX_104}')
ctx.rule(u'AUX_104', u'')
ctx.rule(u'AUX_104', u'{GROUP_104}{AUX_104}')
ctx.rule(u'GROUP_104', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_105', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_106', u'{AUX_105}{EXISTS_T}')
ctx.rule(u'AUX_105', u'')
ctx.rule(u'AUX_105', u'{GROUP_107}')
ctx.rule(u'GROUP_107', u'{NOT_T}')
ctx.rule(u'GROUP_108', u'{WHEN_T}{EXPR}{THEN_T}{EXPR}')
ctx.rule(u'GROUP_109', u'{ELSE_T}{EXPR}')
ctx.rule(u'RAISE_FUNCTION', u'{RAISE_T}{OPEN_PAR_T}{GROUP_110}{CLOSE_PAR_T}')
ctx.rule(u'GROUP_110', u'{IGNORE_T}')
ctx.rule(u'GROUP_110', u'{GROUP_111}{COMMA_T}{ERROR_MESSAGE}')
ctx.rule(u'GROUP_111', u'{ROLLBACK_T}')
ctx.rule(u'GROUP_111', u'{ABORT_T}')
ctx.rule(u'GROUP_111', u'{FAIL_T}')
ctx.rule(u'LITERAL_VALUE', u'{NUMERIC_LITERAL_T}')
ctx.rule(u'LITERAL_VALUE', u'{STRING_LITERAL_T}')
ctx.rule(u'LITERAL_VALUE', u'{BLOB_LITERAL_T}')
ctx.rule(u'LITERAL_VALUE', u'{NULL_T}')
ctx.rule(u'LITERAL_VALUE', u'{TRUE_T}')
ctx.rule(u'LITERAL_VALUE', u'{FALSE_T}')
ctx.rule(u'LITERAL_VALUE', u'{CURRENT_TIME_T}')
ctx.rule(u'LITERAL_VALUE', u'{CURRENT_DATE_T}')
ctx.rule(u'LITERAL_VALUE', u'{CURRENT_TIMESTAMP__T}')
ctx.rule(u'INSERT_STMT', u'{AUX_106}{GROUP_115}{INTO_T}{AUX_107}{TABLE_NAME}{AUX_108}{AUX_109}{GROUP_122}{AUX_110}')
ctx.rule(u'AUX_106', u'')
ctx.rule(u'AUX_106', u'{GROUP_112}')
ctx.rule(u'AUX_107', u'')
ctx.rule(u'AUX_107', u'{GROUP_118}')
ctx.rule(u'AUX_108', u'')
ctx.rule(u'AUX_108', u'{GROUP_119}')
ctx.rule(u'AUX_109', u'')
ctx.rule(u'AUX_109', u'{GROUP_120}')
ctx.rule(u'AUX_110', u'')
ctx.rule(u'AUX_110', u'{RETURNING_CLAUSE}')
ctx.rule(u'GROUP_112', u'{WITH_T}{AUX_111}{COMMON_TABLE_EXPRESSION}{AUX_112}')
ctx.rule(u'AUX_111', u'')
ctx.rule(u'AUX_111', u'{GROUP_113}')
ctx.rule(u'AUX_112', u'')
ctx.rule(u'AUX_112', u'{GROUP_114}{AUX_112}')
ctx.rule(u'GROUP_113', u'{RECURSIVE_T}')
ctx.rule(u'GROUP_114', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_115', u'{INSERT_T}')
ctx.rule(u'GROUP_115', u'{REPLACE_T}')
ctx.rule(u'GROUP_115', u'{GROUP_116}')
ctx.rule(u'GROUP_116', u'{INSERT_T}{OR_T}{GROUP_117}')
ctx.rule(u'GROUP_117', u'{ABORT_T}')
ctx.rule(u'GROUP_117', u'{FAIL_T}')
ctx.rule(u'GROUP_117', u'{IGNORE_T}')
ctx.rule(u'GROUP_117', u'{REPLACE_T}')
ctx.rule(u'GROUP_117', u'{ROLLBACK_T}')
ctx.rule(u'GROUP_118', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_119', u'{AS_T}{TABLE_ALIAS}')
ctx.rule(u'GROUP_120', u'{OPEN_PAR_T}{COLUMN_NAME}{AUX_113}{CLOSE_PAR_T}')
ctx.rule(u'AUX_113', u'')
ctx.rule(u'AUX_113', u'{GROUP_121}{AUX_113}')
ctx.rule(u'GROUP_121', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'GROUP_122', u'{GROUP_123}')
ctx.rule(u'GROUP_122', u'{SELECT_STMT}{AUX_114}')
ctx.rule(u'AUX_114', u'')
ctx.rule(u'AUX_114', u'{UPSERT_CLAUSE}')
ctx.rule(u'GROUP_122', u'{DEFAULT_T}{VALUES_T}')
ctx.rule(u'GROUP_123', u'{VALUES_T}{GROUP_124}{AUX_115}{AUX_116}')
ctx.rule(u'AUX_115', u'')
ctx.rule(u'AUX_115', u'{GROUP_126}{AUX_115}')
ctx.rule(u'AUX_116', u'')
ctx.rule(u'AUX_116', u'{UPSERT_CLAUSE}')
ctx.rule(u'GROUP_124', u'{OPEN_PAR_T}{EXPR}{AUX_117}{CLOSE_PAR_T}')
ctx.rule(u'AUX_117', u'')
ctx.rule(u'AUX_117', u'{GROUP_125}{AUX_117}')
ctx.rule(u'GROUP_125', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_126', u'{COMMA_T}{OPEN_PAR_T}{EXPR}{AUX_118}{CLOSE_PAR_T}')
ctx.rule(u'AUX_118', u'')
ctx.rule(u'AUX_118', u'{GROUP_127}{AUX_118}')
ctx.rule(u'GROUP_127', u'{COMMA_T}{EXPR}')
ctx.rule(u'UPSERT_CLAUSE', u'{ON_T}{CONFLICT_T}{AUX_119}{DO_T}{GROUP_131}')
ctx.rule(u'AUX_119', u'')
ctx.rule(u'AUX_119', u'{GROUP_128}')
ctx.rule(u'GROUP_128', u'{OPEN_PAR_T}{INDEXED_COLUMN}{AUX_120}{CLOSE_PAR_T}{AUX_121}')
ctx.rule(u'AUX_120', u'')
ctx.rule(u'AUX_120', u'{GROUP_129}{AUX_120}')
ctx.rule(u'AUX_121', u'')
ctx.rule(u'AUX_121', u'{GROUP_130}')
ctx.rule(u'GROUP_129', u'{COMMA_T}{INDEXED_COLUMN}')
ctx.rule(u'GROUP_130', u'{WHERE_T}{EXPR}')
ctx.rule(u'GROUP_131', u'{NOTHING_T}')
ctx.rule(u'GROUP_131', u'{UPDATE_T}{SET_T}{GROUP_132}')
ctx.rule(u'GROUP_132', u'{GROUP_133}{ASSIGN_T}{EXPR}{AUX_122}{AUX_123}')
ctx.rule(u'AUX_122', u'')
ctx.rule(u'AUX_122', u'{GROUP_134}{AUX_122}')
ctx.rule(u'AUX_123', u'')
ctx.rule(u'AUX_123', u'{GROUP_136}')
ctx.rule(u'GROUP_133', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_133', u'{COLUMN_NAME_LIST}')
ctx.rule(u'GROUP_134', u'{COMMA_T}{GROUP_135}{ASSIGN_T}{EXPR}')
ctx.rule(u'GROUP_135', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_135', u'{COLUMN_NAME_LIST}')
ctx.rule(u'GROUP_136', u'{WHERE_T}{EXPR}')
ctx.rule(u'PRAGMA_STMT', u'{PRAGMA_T}{AUX_124}{PRAGMA_NAME}{AUX_125}')
ctx.rule(u'AUX_124', u'')
ctx.rule(u'AUX_124', u'{GROUP_137}')
ctx.rule(u'AUX_125', u'')
ctx.rule(u'AUX_125', u'{GROUP_138}')
ctx.rule(u'GROUP_137', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_138', u'{ASSIGN_T}{PRAGMA_VALUE}')
ctx.rule(u'GROUP_138', u'{OPEN_PAR_T}{PRAGMA_VALUE}{CLOSE_PAR_T}')
ctx.rule(u'PRAGMA_VALUE', u'{SIGNED_NUMBER}')
ctx.rule(u'PRAGMA_VALUE', u'{PRAGMA_SPECIAL_VALUE_T}')
ctx.rule(u'PRAGMA_VALUE', u'{DELETE_T}')
ctx.rule(u'PRAGMA_VALUE', u'{EXCLUSIVE_T}')
ctx.rule(u'PRAGMA_VALUE', u'{FULL_T}')
ctx.rule(u'REINDEX_STMT', u'{REINDEX_T}{AUX_126}')
ctx.rule(u'AUX_126', u'')
ctx.rule(u'AUX_126', u'{GROUP_139}')
ctx.rule(u'GROUP_139', u'{COLLATION_NAME}')
ctx.rule(u'GROUP_139', u'{GROUP_140}')
ctx.rule(u'GROUP_140', u'{AUX_127}{GROUP_142}')
ctx.rule(u'AUX_127', u'')
ctx.rule(u'AUX_127', u'{GROUP_141}')
ctx.rule(u'GROUP_141', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_142', u'{TABLE_NAME}')
ctx.rule(u'GROUP_142', u'{INDEX_NAME}')
ctx.rule(u'SELECT_STMT', u'{GROUP_143}')
ctx.rule(u'SELECT_STMT', u'{GROUP_152}')
ctx.rule(u'GROUP_143', u'{AUX_128}{SELECT_CORE}{AUX_129}{AUX_130}{AUX_131}')
ctx.rule(u'AUX_128', u'')
ctx.rule(u'AUX_128', u'{GROUP_144}')
ctx.rule(u'AUX_129', u'')
ctx.rule(u'AUX_129', u'{GROUP_146}{AUX_129}')
ctx.rule(u'AUX_130', u'')
ctx.rule(u'AUX_130', u'{GROUP_147}')
ctx.rule(u'AUX_131', u'')
ctx.rule(u'AUX_131', u'{GROUP_149}')
ctx.rule(u'GROUP_144', u'{WITH_T}{AUX_132}{COMMON_TABLE_EXPRESSION}{AUX_133}')
ctx.rule(u'AUX_132', u'')
ctx.rule(u'AUX_132', u'{RECURSIVE_T}')
ctx.rule(u'AUX_133', u'')
ctx.rule(u'AUX_133', u'{GROUP_145}{AUX_133}')
ctx.rule(u'GROUP_145', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_146', u'{COMPOUND_OPERATOR}{SELECT_CORE}')
ctx.rule(u'GROUP_147', u'{ORDER_T}{BY_T}{ORDERING_TERM}{AUX_134}')
ctx.rule(u'AUX_134', u'')
ctx.rule(u'AUX_134', u'{GROUP_148}{AUX_134}')
ctx.rule(u'GROUP_148', u'{COMMA_T}{ORDERING_TERM}')
ctx.rule(u'GROUP_149', u'{LIMIT_T}{EXPR}{AUX_135}')
ctx.rule(u'AUX_135', u'')
ctx.rule(u'AUX_135', u'{GROUP_150}')
ctx.rule(u'GROUP_150', u'{GROUP_151}{EXPR}')
ctx.rule(u'GROUP_151', u'{OFFSET_T}')
ctx.rule(u'GROUP_151', u'{COMMA_T}')
ctx.rule(u'GROUP_152', u'{AUX_136}{VALUES_STMT}{AUX_137}')
ctx.rule(u'AUX_136', u'')
ctx.rule(u'AUX_136', u'{GROUP_153}')
ctx.rule(u'AUX_137', u'')
ctx.rule(u'AUX_137', u'{GROUP_155}{AUX_137}')
ctx.rule(u'GROUP_153', u'{WITH_T}{AUX_138}{COMMON_TABLE_EXPRESSION}{AUX_139}')
ctx.rule(u'AUX_138', u'')
ctx.rule(u'AUX_138', u'{RECURSIVE_T}')
ctx.rule(u'AUX_139', u'')
ctx.rule(u'AUX_139', u'{GROUP_154}{AUX_139}')
ctx.rule(u'GROUP_154', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_155', u'{COMPOUND_OPERATOR}{VALUES_STMT}')
ctx.rule(u'SELECT_CORE', u'{SELECT_T}{AUX_140}{RESULT_COLUMN}{AUX_141}{AUX_142}{AUX_143}{AUX_144}{AUX_145}')
ctx.rule(u'AUX_140', u'')
ctx.rule(u'AUX_140', u'{GROUP_156}')
ctx.rule(u'AUX_141', u'')
ctx.rule(u'AUX_141', u'{GROUP_157}{AUX_141}')
ctx.rule(u'AUX_142', u'')
ctx.rule(u'AUX_142', u'{GROUP_158}')
ctx.rule(u'AUX_143', u'')
ctx.rule(u'AUX_143', u'{GROUP_162}')
ctx.rule(u'AUX_144', u'')
ctx.rule(u'AUX_144', u'{GROUP_163}')
ctx.rule(u'AUX_145', u'')
ctx.rule(u'AUX_145', u'{GROUP_166}')
ctx.rule(u'GROUP_156', u'{DISTINCT_T}')
ctx.rule(u'GROUP_156', u'{ALL_T}')
ctx.rule(u'GROUP_157', u'{COMMA_T}{RESULT_COLUMN}')
ctx.rule(u'GROUP_158', u'{FROM_T}{GROUP_159}')
ctx.rule(u'GROUP_159', u'{GROUP_160}')
ctx.rule(u'GROUP_159', u'{JOIN_CLAUSE}')
ctx.rule(u'GROUP_160', u'{TABLE_OR_SUBQUERY}{GROUP_161}')
ctx.rule(u'GROUP_161', u'{COMMA_T}{TABLE_OR_SUBQUERY}')
ctx.rule(u'GROUP_162', u'{WHERE_T}{EXPR}')
ctx.rule(u'GROUP_163', u'{GROUP_T}{BY_T}{EXPR}{AUX_146}{AUX_147}')
ctx.rule(u'AUX_146', u'')
ctx.rule(u'AUX_146', u'{GROUP_164}{AUX_146}')
ctx.rule(u'AUX_147', u'')
ctx.rule(u'AUX_147', u'{GROUP_165}')
ctx.rule(u'GROUP_164', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_165', u'{HAVING_T}{EXPR}')
ctx.rule(u'GROUP_166', u'{WINDOW_T}{WINDOW_NAME}{AS_T}{WINDOW_DEFN}{AUX_148}')
ctx.rule(u'AUX_148', u'')
ctx.rule(u'AUX_148', u'{GROUP_167}{AUX_148}')
ctx.rule(u'GROUP_167', u'{COMMA_T}{WINDOW_NAME}{AS_T}{WINDOW_DEFN}')
ctx.rule(u'VALUES_STMT', u'{VALUES_T}{OPEN_PAR_T}{EXPR}{AUX_149}{CLOSE_PAR_T}{AUX_150}')
ctx.rule(u'AUX_149', u'')
ctx.rule(u'AUX_149', u'{GROUP_168}{AUX_149}')
ctx.rule(u'AUX_150', u'')
ctx.rule(u'AUX_150', u'{GROUP_169}{AUX_150}')
ctx.rule(u'GROUP_168', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_169', u'{COMMA_T}{OPEN_PAR_T}{EXPR}{AUX_151}{CLOSE_PAR_T}')
ctx.rule(u'AUX_151', u'')
ctx.rule(u'AUX_151', u'{GROUP_170}{AUX_151}')
ctx.rule(u'GROUP_170', u'{COMMA_T}{EXPR}')
ctx.rule(u'JOIN_CLAUSE', u'{TABLE_OR_SUBQUERY}{AUX_152}')
ctx.rule(u'AUX_152', u'')
ctx.rule(u'AUX_152', u'{GROUP_171}{AUX_152}')
ctx.rule(u'GROUP_171', u'{JOIN_OPERATOR}{TABLE_OR_SUBQUERY}{JOIN_CONSTRAINT}')
ctx.rule(u'TABLE_OR_SUBQUERY', u'{GROUP_172}')
ctx.rule(u'TABLE_OR_SUBQUERY', u'{OPEN_PAR_T}{SELECT_STMT}{CLOSE_PAR_T}{AUX_153}')
ctx.rule(u'AUX_153', u'')
ctx.rule(u'AUX_153', u'{GROUP_178}')
ctx.rule(u'TABLE_OR_SUBQUERY', u'{OPEN_PAR_T}{GROUP_179}{CLOSE_PAR_T}')
ctx.rule(u'GROUP_172', u'{AUX_154}{TABLE_NAME}{AUX_155}{AUX_156}')
ctx.rule(u'AUX_154', u'')
ctx.rule(u'AUX_154', u'{GROUP_173}')
ctx.rule(u'AUX_155', u'')
ctx.rule(u'AUX_155', u'{GROUP_174}')
ctx.rule(u'AUX_156', u'')
ctx.rule(u'AUX_156', u'{GROUP_175}')
ctx.rule(u'GROUP_173', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_174', u'{AUX_157}{TABLE_ALIAS}')
ctx.rule(u'AUX_157', u'')
ctx.rule(u'AUX_157', u'{AS_T}')
ctx.rule(u'GROUP_175', u'{GROUP_176}')
ctx.rule(u'GROUP_175', u'{GROUP_177}')
ctx.rule(u'GROUP_176', u'{INDEXED_T}{BY_T}{INDEX_NAME}')
ctx.rule(u'GROUP_177', u'{NOT_T}{INDEXED_T}')
ctx.rule(u'GROUP_178', u'{AUX_158}{TABLE_ALIAS}')
ctx.rule(u'AUX_158', u'')
ctx.rule(u'AUX_158', u'{AS_T}')
ctx.rule(u'GROUP_179', u'{GROUP_180}')
ctx.rule(u'GROUP_179', u'{JOIN_CLAUSE}')
ctx.rule(u'GROUP_180', u'{TABLE_OR_SUBQUERY}{AUX_159}')
ctx.rule(u'AUX_159', u'')
ctx.rule(u'AUX_159', u'{GROUP_181}{AUX_159}')
ctx.rule(u'GROUP_181', u'{COMMA_T}{TABLE_OR_SUBQUERY}')
ctx.rule(u'RESULT_COLUMN', u'{STAR_T}')
ctx.rule(u'RESULT_COLUMN', u'{TABLE_NAME}{DOT_T}{STAR_T}')
ctx.rule(u'RESULT_COLUMN', u'{EXPR}{AUX_160}')
ctx.rule(u'AUX_160', u'')
ctx.rule(u'AUX_160', u'{GROUP_182}')
ctx.rule(u'GROUP_182', u'{AUX_161}{COLUMN_ALIAS}')
ctx.rule(u'AUX_161', u'')
ctx.rule(u'AUX_161', u'{AS_T}')
ctx.rule(u'JOIN_OPERATOR', u'{COMMA_T}')
ctx.rule(u'JOIN_OPERATOR', u'{AUX_162}{AUX_163}{JOIN_T}')
ctx.rule(u'AUX_162', u'')
ctx.rule(u'AUX_162', u'{NATURAL_T}')
ctx.rule(u'AUX_163', u'')
ctx.rule(u'AUX_163', u'{GROUP_183}')
ctx.rule(u'GROUP_183', u'{LEFT_T}{AUX_164}')
ctx.rule(u'AUX_164', u'')
ctx.rule(u'AUX_164', u'{OUTER_T}')
ctx.rule(u'GROUP_183', u'{INNER_T}')
ctx.rule(u'GROUP_183', u'{CROSS_T}')
ctx.rule(u'JOIN_CONSTRAINT', u'{AUX_165}')
ctx.rule(u'AUX_165', u'')
ctx.rule(u'AUX_165', u'{GROUP_184}')
ctx.rule(u'GROUP_184', u'{ON_T}{EXPR}')
ctx.rule(u'GROUP_184', u'{USING_T}{OPEN_PAR_T}{COLUMN_NAME}{AUX_166}{CLOSE_PAR_T}')
ctx.rule(u'AUX_166', u'')
ctx.rule(u'AUX_166', u'{GROUP_185}{AUX_166}')
ctx.rule(u'GROUP_185', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'COMPOUND_OPERATOR', u'{GROUP_186}')
ctx.rule(u'COMPOUND_OPERATOR', u'{INTERSECT_T}')
ctx.rule(u'COMPOUND_OPERATOR', u'{EXCEPT_T}')
ctx.rule(u'GROUP_186', u'{UNION_T}{AUX_167}')
ctx.rule(u'AUX_167', u'')
ctx.rule(u'AUX_167', u'{ALL_T}')
ctx.rule(u'UPDATE_STMT', u'{AUX_168}{UPDATE_T}{AUX_169}{QUALIFIED_TABLE_NAME}{SET_T}{GROUP_191}{ASSIGN_T}{EXPR}{AUX_170}{AUX_171}{AUX_172}{AUX_173}')
ctx.rule(u'AUX_168', u'')
ctx.rule(u'AUX_168', u'{GROUP_187}')
ctx.rule(u'AUX_169', u'')
ctx.rule(u'AUX_169', u'{GROUP_189}')
ctx.rule(u'AUX_170', u'')
ctx.rule(u'AUX_170', u'{GROUP_192}{AUX_170}')
ctx.rule(u'AUX_171', u'')
ctx.rule(u'AUX_171', u'{GROUP_194}')
ctx.rule(u'AUX_172', u'')
ctx.rule(u'AUX_172', u'{GROUP_198}')
ctx.rule(u'AUX_173', u'')
ctx.rule(u'AUX_173', u'{RETURNING_CLAUSE}')
ctx.rule(u'GROUP_187', u'{WITH_T}{AUX_174}{COMMON_TABLE_EXPRESSION}{AUX_175}')
ctx.rule(u'AUX_174', u'')
ctx.rule(u'AUX_174', u'{RECURSIVE_T}')
ctx.rule(u'AUX_175', u'')
ctx.rule(u'AUX_175', u'{GROUP_188}{AUX_175}')
ctx.rule(u'GROUP_188', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_189', u'{OR_T}{GROUP_190}')
ctx.rule(u'GROUP_190', u'{ABORT_T}')
ctx.rule(u'GROUP_190', u'{FAIL_T}')
ctx.rule(u'GROUP_190', u'{IGNORE_T}')
ctx.rule(u'GROUP_190', u'{REPLACE_T}')
ctx.rule(u'GROUP_190', u'{ROLLBACK_T}')
ctx.rule(u'GROUP_191', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_191', u'{COLUMN_NAME_LIST}')
ctx.rule(u'GROUP_192', u'{COMMA_T}{GROUP_193}{ASSIGN_T}{EXPR}')
ctx.rule(u'GROUP_193', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_193', u'{COLUMN_NAME_LIST}')
ctx.rule(u'GROUP_194', u'{FROM_T}{GROUP_195}')
ctx.rule(u'GROUP_195', u'{GROUP_196}')
ctx.rule(u'GROUP_195', u'{JOIN_CLAUSE}')
ctx.rule(u'GROUP_196', u'{TABLE_OR_SUBQUERY}{AUX_176}')
ctx.rule(u'AUX_176', u'')
ctx.rule(u'AUX_176', u'{GROUP_197}{AUX_176}')
ctx.rule(u'GROUP_197', u'{COMMA_T}{TABLE_OR_SUBQUERY}')
ctx.rule(u'GROUP_198', u'{WHERE_T}{EXPR}')
ctx.rule(u'COLUMN_NAME_LIST', u'{OPEN_PAR_T}{COLUMN_NAME}{AUX_177}{CLOSE_PAR_T}')
ctx.rule(u'AUX_177', u'')
ctx.rule(u'AUX_177', u'{GROUP_199}{AUX_177}')
ctx.rule(u'GROUP_199', u'{COMMA_T}{COLUMN_NAME}')
ctx.rule(u'UPDATE_STMT_LIMITED', u'{AUX_178}{UPDATE_T}{AUX_179}{QUALIFIED_TABLE_NAME}{SET_T}{GROUP_204}{ASSIGN_T}{EXPR}{AUX_180}{AUX_181}{AUX_182}{AUX_183}{AUX_184}{AUX_185}')
ctx.rule(u'AUX_178', u'')
ctx.rule(u'AUX_178', u'{GROUP_200}')
ctx.rule(u'AUX_179', u'')
ctx.rule(u'AUX_179', u'{GROUP_202}')
ctx.rule(u'AUX_180', u'')
ctx.rule(u'AUX_180', u'{GROUP_205}{AUX_180}')
ctx.rule(u'AUX_181', u'')
ctx.rule(u'AUX_181', u'{GROUP_207}')
ctx.rule(u'AUX_182', u'')
ctx.rule(u'AUX_182', u'{GROUP_211}')
ctx.rule(u'AUX_183', u'')
ctx.rule(u'AUX_183', u'{RETURNING_CLAUSE}')
ctx.rule(u'AUX_184', u'')
ctx.rule(u'AUX_184', u'{GROUP_212}')
ctx.rule(u'AUX_185', u'')
ctx.rule(u'AUX_185', u'{GROUP_214}')
ctx.rule(u'GROUP_200', u'{WITH_T}{AUX_186}{COMMON_TABLE_EXPRESSION}{AUX_187}')
ctx.rule(u'AUX_186', u'')
ctx.rule(u'AUX_186', u'{RECURSIVE_T}')
ctx.rule(u'AUX_187', u'')
ctx.rule(u'AUX_187', u'{GROUP_201}{AUX_187}')
ctx.rule(u'GROUP_201', u'{COMMA_T}{COMMON_TABLE_EXPRESSION}')
ctx.rule(u'GROUP_202', u'{OR_T}{GROUP_203}')
ctx.rule(u'GROUP_203', u'{ABORT_T}')
ctx.rule(u'GROUP_203', u'{FAIL_T}')
ctx.rule(u'GROUP_203', u'{IGNORE_T}')
ctx.rule(u'GROUP_203', u'{REPLACE_T}')
ctx.rule(u'GROUP_203', u'{ROLLBACK_T}')
ctx.rule(u'GROUP_204', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_204', u'{COLUMN_NAME_LIST}')
ctx.rule(u'GROUP_205', u'{COMMA_T}{GROUP_206}{ASSIGN_T}{EXPR}')
ctx.rule(u'GROUP_206', u'{COLUMN_NAME}')
ctx.rule(u'GROUP_206', u'{COLUMN_NAME_LIST}')
ctx.rule(u'GROUP_207', u'{FROM_T}{GROUP_208}')
ctx.rule(u'GROUP_208', u'{GROUP_209}')
ctx.rule(u'GROUP_208', u'{JOIN_CLAUSE}')
ctx.rule(u'GROUP_209', u'{TABLE_OR_SUBQUERY}{AUX_188}')
ctx.rule(u'AUX_188', u'')
ctx.rule(u'AUX_188', u'{GROUP_210}{AUX_188}')
ctx.rule(u'GROUP_210', u'{COMMA_T}{TABLE_OR_SUBQUERY}')
ctx.rule(u'GROUP_211', u'{WHERE_T}{EXPR}')
ctx.rule(u'GROUP_212', u'{ORDER_T}{BY_T}{ORDERING_TERM}{AUX_189}')
ctx.rule(u'AUX_189', u'')
ctx.rule(u'AUX_189', u'{GROUP_213}{AUX_189}')
ctx.rule(u'GROUP_213', u'{COMMA_T}{ORDERING_TERM}')
ctx.rule(u'GROUP_214', u'{LIMIT_T}{EXPR}{AUX_190}')
ctx.rule(u'AUX_190', u'')
ctx.rule(u'AUX_190', u'{GROUP_215}')
ctx.rule(u'GROUP_215', u'{GROUP_216}{EXPR}')
ctx.rule(u'GROUP_216', u'{OFFSET_T}')
ctx.rule(u'GROUP_216', u'{COMMA_T}')
ctx.rule(u'QUALIFIED_TABLE_NAME', u'{AUX_191}{TABLE_NAME}{AUX_192}{AUX_193}')
ctx.rule(u'AUX_191', u'')
ctx.rule(u'AUX_191', u'{GROUP_217}')
ctx.rule(u'AUX_192', u'')
ctx.rule(u'AUX_192', u'{GROUP_218}')
ctx.rule(u'AUX_193', u'')
ctx.rule(u'AUX_193', u'{GROUP_219}')
ctx.rule(u'GROUP_217', u'{SCHEMA_NAME}{DOT_T}')
ctx.rule(u'GROUP_218', u'{AS_T}{ALIAS}')
ctx.rule(u'GROUP_219', u'{INDEXED_T}{BY_T}{INDEX_NAME}')
ctx.rule(u'GROUP_219', u'{NOT_T}{INDEXED_T}')
ctx.rule(u'VACUUM_STMT', u'{VACUUM_T}{AUX_194}')
ctx.rule(u'AUX_194', u'')
ctx.rule(u'AUX_194', u'{SCHEMA_NAME}')
ctx.rule(u'FILTER_CLAUSE', u'{FILTER_T}{OPEN_PAR_T}{WHERE_T}{EXPR}{CLOSE_PAR_T}')
ctx.rule(u'WINDOW_DEFN', u'{OPEN_PAR_T}{AUX_195}{AUX_196}{AUX_197}{AUX_198}{CLOSE_PAR_T}')
ctx.rule(u'AUX_195', u'')
ctx.rule(u'AUX_195', u'{BASE_WINDOW_NAME}')
ctx.rule(u'AUX_196', u'')
ctx.rule(u'AUX_196', u'{GROUP_220}')
ctx.rule(u'AUX_197', u'')
ctx.rule(u'AUX_197', u'{GROUP_222}')
ctx.rule(u'AUX_198', u'')
ctx.rule(u'AUX_198', u'{FRAME_SPEC}')
ctx.rule(u'GROUP_220', u'{PARTITION_T}{BY_T}{EXPR}{AUX_199}')
ctx.rule(u'AUX_199', u'')
ctx.rule(u'AUX_199', u'{GROUP_221}{AUX_199}')
ctx.rule(u'GROUP_221', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_222', u'{ORDER_T}{BY_T}{ORDERING_TERM}{AUX_200}')
ctx.rule(u'AUX_200', u'')
ctx.rule(u'AUX_200', u'{GROUP_223}{AUX_200}')
ctx.rule(u'GROUP_223', u'{COMMA_T}{ORDERING_TERM}')
ctx.rule(u'FRAME_SPEC', u'{GROUP_224}{GROUP_225}{AUX_201}')
ctx.rule(u'AUX_201', u'')
ctx.rule(u'AUX_201', u'{GROUP_229}')
ctx.rule(u'GROUP_224', u'{RANGE_T}')
ctx.rule(u'GROUP_224', u'{ROWS_T}')
ctx.rule(u'GROUP_224', u'{GROUPS_T}')
ctx.rule(u'GROUP_225', u'{GROUP_226}')
ctx.rule(u'GROUP_225', u'{UNBOUNDED_T}{PRECEDING_T}')
ctx.rule(u'GROUP_225', u'{EXPR}{PRECEDING_T}')
ctx.rule(u'GROUP_225', u'{CURRENT_T}{ROW_T}')
ctx.rule(u'GROUP_226', u'{BETWEEN_T}{GROUP_227}{AND_T}{GROUP_228}')
ctx.rule(u'GROUP_227', u'{UNBOUNDED_T}{PRECEDING_T}')
ctx.rule(u'GROUP_227', u'{EXPR}{PRECEDING_T}')
ctx.rule(u'GROUP_227', u'{CURRENT_T}{ROW_T}')
ctx.rule(u'GROUP_227', u'{EXPR}{FOLLOWING_T}')
ctx.rule(u'GROUP_228', u'{EXPR}{PRECEDING_T}')
ctx.rule(u'GROUP_228', u'{CURRENT_T}{ROW_T}')
ctx.rule(u'GROUP_228', u'{EXPR}{FOLLOWING_T}')
ctx.rule(u'GROUP_228', u'{UNBOUNDED_T}{FOLLOWING_T}')
ctx.rule(u'GROUP_229', u'{EXCLUDE_T}{GROUP_230}')
ctx.rule(u'GROUP_230', u'{NO_T}{OTHERS_T}')
ctx.rule(u'GROUP_230', u'{CURRENT_T}{ROW_T}')
ctx.rule(u'GROUP_230', u'{GROUP_T}')
ctx.rule(u'GROUP_230', u'{TIES_T}')
ctx.rule(u'ORDERING_TERM', u'{EXPR}{AUX_202}{AUX_203}{AUX_204}')
ctx.rule(u'AUX_202', u'')
ctx.rule(u'AUX_202', u'{GROUP_231}')
ctx.rule(u'AUX_203', u'')
ctx.rule(u'AUX_203', u'{GROUP_232}')
ctx.rule(u'AUX_204', u'')
ctx.rule(u'AUX_204', u'{GROUP_233}')
ctx.rule(u'GROUP_231', u'{COLLATE_T}{COLLATION_NAME}')
ctx.rule(u'GROUP_232', u'{ASC_T}')
ctx.rule(u'GROUP_232', u'{DESC_T}')
ctx.rule(u'GROUP_233', u'{NULLS_T}{GROUP_234}')
ctx.rule(u'GROUP_234', u'{FIRST_T}')
ctx.rule(u'GROUP_234', u'{LAST_T}')
ctx.rule(u'RETURNING_CLAUSE', u'{RETURNING_T}{GROUP_235}{AUX_205}')
ctx.rule(u'AUX_205', u'')
ctx.rule(u'AUX_205', u'{GROUP_238}{AUX_205}')
ctx.rule(u'GROUP_235', u'{GROUP_236}')
ctx.rule(u'GROUP_235', u'{STAR_T}')
ctx.rule(u'GROUP_236', u'{EXPR}{AUX_206}')
ctx.rule(u'AUX_206', u'')
ctx.rule(u'AUX_206', u'{GROUP_237}')
ctx.rule(u'GROUP_237', u'{AUX_207}{COLUMN_ALIAS}')
ctx.rule(u'AUX_207', u'')
ctx.rule(u'AUX_207', u'{AS_T}')
ctx.rule(u'GROUP_238', u'{COMMA_T}{GROUP_239}')
ctx.rule(u'GROUP_239', u'{GROUP_240}')
ctx.rule(u'GROUP_239', u'{STAR_T}')
ctx.rule(u'GROUP_240', u'{EXPR}{AUX_208}')
ctx.rule(u'AUX_208', u'')
ctx.rule(u'AUX_208', u'{GROUP_241}')
ctx.rule(u'GROUP_241', u'{AUX_209}{COLUMN_ALIAS}')
ctx.rule(u'AUX_209', u'')
ctx.rule(u'AUX_209', u'{AS_T}')
ctx.rule(u'UNARY_OPERATOR', u'{MINUS_T}')
ctx.rule(u'UNARY_OPERATOR', u'{PLUS_T}')
ctx.rule(u'UNARY_OPERATOR', u'{TILDE_T}')
ctx.rule(u'UNARY_OPERATOR', u'{NOT_T}')
ctx.rule(u'ERROR_MESSAGE', u'{ERROR_MESSAGE_T}')
ctx.rule(u'COLUMN_ALIAS', u'{COLUMN_NAME}')
ctx.rule(u'SCHEMA_NAME', u'{SCHEMA_NAME_T}')
ctx.rule(u'TABLE_NAME', u'{TABLE_NAME_T}')
ctx.rule(u'INDEX_OR_TABLE_NAME', u'{TABLE_NAME_T}')
ctx.rule(u'INDEX_OR_TABLE_NAME', u'{INDEX_NAME_T}')
ctx.rule(u'NEW_TABLE_NAME', u'{TABLE_NAME_T}')
ctx.rule(u'COLUMN_NAME', u'{COLUMN_NAME_T}')
ctx.rule(u'COLLATION_NAME', u'{COLLATION_NAME_T}')
ctx.rule(u'FOREIGN_TABLE', u'{TABLE_NAME_T}')
ctx.rule(u'INDEX_NAME', u'{INDEX_NAME_T}')
ctx.rule(u'TRIGGER_NAME', u'{TRIGGER_NAME_T}')
ctx.rule(u'VIEW_NAME', u'{VIEW_NAME_T}')
ctx.rule(u'PRAGMA_NAME', u'{PRAGMA_NAME_T}')
ctx.rule(u'SAVEPOINT_NAME', u'{SAVEPOINT_NAME_T}')
ctx.rule(u'TABLE_ALIAS', u'{TABLE_NAME_T}')
ctx.rule(u'WINDOW_NAME', u'{WINDOW_NAME_T}')
ctx.rule(u'ALIAS', u'{TABLE_NAME_T}')
ctx.rule(u'BASE_WINDOW_NAME', u'{WINDOW_NAME_T}')
ctx.rule(u'FUNCTION', u'{SIMPLE_FUNC}')
ctx.rule(u'FUNCTION', u'{AGGREGATE_FUNC}')
ctx.rule(u'FUNCTION', u'{WINDOW_FUNC}')
ctx.rule(u'SIMPLE_FUNC', u'{GROUP_242}{OPEN_PAR_T}{AUX_210}{CLOSE_PAR_T}')
ctx.rule(u'AUX_210', u'')
ctx.rule(u'AUX_210', u'{GROUP_243}')
ctx.rule(u'GROUP_242', u'{SIMPLE_FUNC_NAME_T}')
ctx.rule(u'GROUP_242', u'{MAX_T}')
ctx.rule(u'GROUP_242', u'{MIN_T}')
ctx.rule(u'GROUP_243', u'{GROUP_244}')
ctx.rule(u'GROUP_243', u'{STAR_T}')
ctx.rule(u'GROUP_244', u'{EXPR}{AUX_211}')
ctx.rule(u'AUX_211', u'')
ctx.rule(u'AUX_211', u'{GROUP_245}{AUX_211}')
ctx.rule(u'GROUP_245', u'{COMMA_T}{EXPR}')
ctx.rule(u'AGGREGATE_FUNC', u'{GROUP_246}{OPEN_PAR_T}{AUX_212}{CLOSE_PAR_T}{AUX_213}')
ctx.rule(u'AUX_212', u'')
ctx.rule(u'AUX_212', u'{GROUP_247}')
ctx.rule(u'AUX_213', u'')
ctx.rule(u'AUX_213', u'{FILTER_CLAUSE}')
ctx.rule(u'GROUP_246', u'{AGGREGATE_FUNC_NAME_T}')
ctx.rule(u'GROUP_246', u'{MAX_T}')
ctx.rule(u'GROUP_246', u'{MIN_T}')
ctx.rule(u'GROUP_247', u'{GROUP_248}')
ctx.rule(u'GROUP_247', u'{STAR_T}')
ctx.rule(u'GROUP_248', u'{AUX_214}{GROUP_249}')
ctx.rule(u'AUX_214', u'')
ctx.rule(u'AUX_214', u'{DISTINCT_T}')
ctx.rule(u'GROUP_249', u'{EXPR}{AUX_215}')
ctx.rule(u'AUX_215', u'')
ctx.rule(u'AUX_215', u'{GROUP_250}{AUX_215}')
ctx.rule(u'GROUP_250', u'{COMMA_T}{EXPR}')
ctx.rule(u'WINDOW_FUNC', u'{WINDOW_FUNC_NAME_T}{OPEN_PAR_T}{AUX_216}{CLOSE_PAR_T}{AUX_217}{OVER_T}{GROUP_254}')
ctx.rule(u'AUX_216', u'')
ctx.rule(u'AUX_216', u'{GROUP_251}')
ctx.rule(u'AUX_217', u'')
ctx.rule(u'AUX_217', u'{FILTER_CLAUSE}')
ctx.rule(u'GROUP_251', u'{GROUP_252}')
ctx.rule(u'GROUP_251', u'{STAR_T}')
ctx.rule(u'GROUP_252', u'{EXPR}{AUX_218}')
ctx.rule(u'AUX_218', u'')
ctx.rule(u'AUX_218', u'{GROUP_253}{AUX_218}')
ctx.rule(u'GROUP_253', u'{COMMA_T}{EXPR}')
ctx.rule(u'GROUP_254', u'{WINDOW_DEFN}')
ctx.rule(u'GROUP_254', u'{WINDOW_NAME}')
ctx.rule(u'SCOL_T', u';')
ctx.rule(u'DOT_T', u'.')
ctx.rule(u'OPEN_PAR_T', u'(')
ctx.rule(u'CLOSE_PAR_T', u')')
ctx.rule(u'COMMA_T', u', ')
ctx.rule(u'ASSIGN_T', u'=')
ctx.rule(u'STAR_T', u'*')
ctx.rule(u'PLUS_T', u'+')
ctx.rule(u'MINUS_T', u'-')
ctx.rule(u'TILDE_T', u'~')
ctx.rule(u'PIPE2_', u'||')
ctx.rule(u'DIV_T', u'/')
ctx.rule(u'MOD_T', u'%')
ctx.rule(u'LT2_', u'<<')
ctx.rule(u'GT2_', u'>>')
ctx.rule(u'AMP_T', u'&')
ctx.rule(u'PIPE_T', u'|')
ctx.rule(u'LT_T', u'<')
ctx.rule(u'LT_EQ_T', u'<=')
ctx.rule(u'GT_T', u'>')
ctx.rule(u'GT_EQ_T', u'>=')
ctx.rule(u'EQ_T', u'==')
ctx.rule(u'NOT_EQ1_', u'!=')
ctx.rule(u'NOT_EQ2_', u'<>')
ctx.rule(u'R_ARR1_', u'->')
ctx.rule(u'R_ARR2_', u'->>')
ctx.rule(u'ABORT_T', u' ABORT ')
ctx.rule(u'ACTION_T', u' ACTION ')
ctx.rule(u'ADD_T', u' ADD ')
ctx.rule(u'AFTER_T', u' AFTER ')
ctx.rule(u'ALL_T', u' ALL ')
ctx.rule(u'ALTER_T', u' ALTER ')
ctx.rule(u'ANALYZE_T', u' ANALYZE ')
ctx.rule(u'AND_T', u' AND ')
ctx.rule(u'AS_T', u' AS ')
ctx.rule(u'ASC_T', u' ASC ')
ctx.rule(u'ATTACH_T', u' ATTACH ')
ctx.rule(u'AUTOINCREMENT_T', u' AUTOINCREMENT ')
ctx.rule(u'BEFORE_T', u' BEFORE ')
ctx.rule(u'BEGIN_T', u' BEGIN ')
ctx.rule(u'BETWEEN_T', u' BETWEEN ')
ctx.rule(u'BY_T', u' BY ')
ctx.rule(u'CASCADE_T', u' CASCADE ')
ctx.rule(u'CASE_T', u' CASE ')
ctx.rule(u'CAST_T', u' CAST ')
ctx.rule(u'CHECK_T', u' CHECK ')
ctx.rule(u'COLLATE_T', u' COLLATE ')
ctx.rule(u'COLUMN_T', u' COLUMN ')
ctx.rule(u'COMMIT_T', u' COMMIT ')
ctx.rule(u'CONFLICT_T', u' CONFLICT ')
ctx.rule(u'CONSTRAINT_T', u' CONSTRAINT ')
ctx.rule(u'CREATE_T', u' CREATE ')
ctx.rule(u'CROSS_T', u' CROSS ')
ctx.rule(u'CURRENT_DATE_T', u' CURRENT_DATE ')
ctx.rule(u'CURRENT_TIME_T', u' CURRENT_TIME ')
ctx.rule(u'CURRENT_TIMESTAMP__T', u' CURRENT_TIMESTAMP_T ')
ctx.rule(u'DATABASE_T', u' DATABASE ')
ctx.rule(u'DEFAULT_T', u' DEFAULT ')
ctx.rule(u'DEFERRABLE_T', u' DEFERRABLE ')
ctx.rule(u'DEFERRED_T', u' DEFERRED ')
ctx.rule(u'DELETE_T', u' DELETE ')
ctx.rule(u'DESC_T', u' DESC ')
ctx.rule(u'DETACH_T', u' DETACH ')
ctx.rule(u'DISTINCT_T', u' DISTINCT ')
ctx.rule(u'DROP_T', u' DROP ')
ctx.rule(u'EACH_T', u' EACH ')
ctx.rule(u'ELSE_T', u' ELSE ')
ctx.rule(u'END_T', u' END ')
ctx.rule(u'ESCAPE_T', u' ESCAPE ')
ctx.rule(u'EXCEPT_T', u' EXCEPT ')
ctx.rule(u'EXCLUSIVE_T', u' EXCLUSIVE ')
ctx.rule(u'EXISTS_T', u' EXISTS ')
ctx.rule(u'EXPLAIN_T', u' EXPLAIN ')
ctx.rule(u'FAIL_T', u' FAIL ')
ctx.rule(u'FOR_T', u' FOR ')
ctx.rule(u'FOREIGN_T', u' FOREIGN ')
ctx.rule(u'FROM_T', u' FROM ')
ctx.rule(u'FULL_T', u' FULL ')
ctx.rule(u'GLOB_T', u' GLOB ')
ctx.rule(u'GROUP_T', u' GROUP ')
ctx.rule(u'HAVING_T', u' HAVING ')
ctx.rule(u'IF_T', u' IF ')
ctx.rule(u'IGNORE_T', u' IGNORE ')
ctx.rule(u'IMMEDIATE_T', u' IMMEDIATE ')
ctx.rule(u'IN_T', u' IN ')
ctx.rule(u'INDEX_T', u' INDEX ')
ctx.rule(u'INDEXED_T', u' INDEXED ')
ctx.rule(u'INITIALLY_T', u' INITIALLY ')
ctx.rule(u'INNER_T', u' INNER ')
ctx.rule(u'INSERT_T', u' INSERT ')
ctx.rule(u'INSTEAD_T', u' INSTEAD ')
ctx.rule(u'INTERSECT_T', u' INTERSECT ')
ctx.rule(u'INTO_T', u' INTO ')
ctx.rule(u'IS_T', u' IS ')
ctx.rule(u'ISNULL_T', u' ISNULL ')
ctx.rule(u'JOIN_T', u' JOIN ')
ctx.rule(u'KEY_T', u' KEY ')
ctx.rule(u'LEFT_T', u' LEFT ')
ctx.rule(u'LIKE_T', u' LIKE ')
ctx.rule(u'LIMIT_T', u' LIMIT ')
ctx.rule(u'MATCH_T', u' MATCH ')
ctx.rule(u'MATERIALIZED_T', u' MATERIALIZED ')
ctx.rule(u'NATURAL_T', u' NATURAL ')
ctx.rule(u'NO_T', u' NO ')
ctx.rule(u'NOT_T', u' NOT ')
ctx.rule(u'NOTNULL_T', u' NOTNULL ')
ctx.rule(u'NULL_T', u' NULL ')
ctx.rule(u'OF_T', u' OF ')
ctx.rule(u'OFFSET_T', u' OFFSET ')
ctx.rule(u'ON_T', u' ON ')
ctx.rule(u'OR_T', u' OR ')
ctx.rule(u'ORDER_T', u' ORDER ')
ctx.rule(u'OUTER_T', u' OUTER ')
ctx.rule(u'PLAN_T', u' PLAN ')
ctx.rule(u'PRAGMA_T', u' PRAGMA ')
ctx.rule(u'PRIMARY_T', u' PRIMARY ')
ctx.rule(u'QUERY_T', u' QUERY ')
ctx.rule(u'RAISE_T', u' RAISE ')
ctx.rule(u'RECURSIVE_T', u' RECURSIVE ')
ctx.rule(u'REFERENCES_T', u' REFERENCES ')
ctx.rule(u'REGEXP_T', u' REGEXP ')
ctx.rule(u'REINDEX_T', u' REINDEX ')
ctx.rule(u'RELEASE_T', u' RELEASE ')
ctx.rule(u'RENAME_T', u' RENAME ')
ctx.rule(u'REPLACE_T', u' REPLACE ')
ctx.rule(u'RESTRICT_T', u' RESTRICT ')
ctx.rule(u'ROLLBACK_T', u' ROLLBACK ')
ctx.rule(u'ROW_T', u' ROW ')
ctx.rule(u'ROWID_T', u' ROWID ')
ctx.rule(u'ROWS_T', u' ROWS ')
ctx.rule(u'SAVEPOINT_T', u' SAVEPOINT ')
ctx.rule(u'SELECT_T', u' SELECT ')
ctx.rule(u'SET_T', u' SET ')
ctx.rule(u'STRICT_T', u' STRICT ')
ctx.rule(u'TABLE_T', u' TABLE ')
ctx.rule(u'TEMP_T', u' TEMP ')
ctx.rule(u'TEMPORARY_T', u' TEMPORARY ')
ctx.rule(u'THEN_T', u' THEN ')
ctx.rule(u'TO_T', u' TO ')
ctx.rule(u'TRANSACTION_T', u' TRANSACTION ')
ctx.rule(u'TRIGGER_T', u' TRIGGER ')
ctx.rule(u'UNION_T', u' UNION ')
ctx.rule(u'UNIQUE_T', u' UNIQUE ')
ctx.rule(u'UPDATE_T', u' UPDATE ')
ctx.rule(u'USING_T', u' USING ')
ctx.rule(u'VACUUM_T', u' VACUUM ')
ctx.rule(u'VALUES_T', u' VALUES ')
ctx.rule(u'VIEW_T', u' VIEW ')
ctx.rule(u'VIRTUAL_T', u' VIRTUAL ')
ctx.rule(u'WHEN_T', u' WHEN ')
ctx.rule(u'WHERE_T', u' WHERE ')
ctx.rule(u'WITH_T', u' WITH ')
ctx.rule(u'WITHOUT_T', u' WITHOUT ')
ctx.rule(u'OVER_T', u' OVER ')
ctx.rule(u'PARTITION_T', u' PARTITION ')
ctx.rule(u'RANGE_T', u' RANGE ')
ctx.rule(u'RETURNING_T', u' RETURNING ')
ctx.rule(u'PRECEDING_T', u' PRECEDING ')
ctx.rule(u'UNBOUNDED_T', u' UNBOUNDED ')
ctx.rule(u'CURRENT_T', u' CURRENT ')
ctx.rule(u'FOLLOWING_T', u' FOLLOWING ')
ctx.rule(u'GENERATED_T', u' GENERATED ')
ctx.rule(u'ALWAYS_T', u' ALWAYS ')
ctx.rule(u'STORED_T', u' STORED ')
ctx.rule(u'TRUE_T', u' TRUE ')
ctx.rule(u'FALSE_T', u' FALSE ')
ctx.rule(u'WINDOW_T', u' WINDOW ')
ctx.rule(u'NULLS_T', u' NULLS ')
ctx.rule(u'FIRST_T', u' FIRST ')
ctx.rule(u'LAST_T', u' LAST ')
ctx.rule(u'FILTER_T', u' FILTER ')
ctx.rule(u'GROUPS_T', u' GROUPS ')
ctx.rule(u'EXCLUDE_T', u' EXCLUDE ')
ctx.rule(u'TIES_T', u' TIES ')
ctx.rule(u'OTHERS_T', u' OTHERS ')
ctx.rule(u'DO_T', u' DO ')
ctx.rule(u'NOTHING_T', u' NOTHING ')
ctx.rule(u'COLLATION_NAME_T', u'BINARY')
ctx.rule(u'COLLATION_NAME_T', u'NOCASE')
ctx.rule(u'COLLATION_NAME_T', u'RTRIM')
ctx.rule(u'MIN_T', u'min')
ctx.rule(u'MAX_T', u'max')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'abs')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'changes')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'char')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'coalesce')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'format')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'glob')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'hex')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'ifnull')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'iif')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'instr')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'last_insert_rowid')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'length')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'like')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'likelihood')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'likely')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'load_extension')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'lower')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'ltrim')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'nullif')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'printf')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'quote')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'random')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'randomblob')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'replace')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'round')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'rtrim')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'sign')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'soundex')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'sqlite_compileoption_get')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'sqlite_compileoption_used')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'sqlite_offset')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'sqlite_source_id')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'sqlite_version')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'substr')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'substring')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'total_changes')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'trim')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'typeof')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'unicode')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'unlikely')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'upper')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'zeroblob')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'date')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'time')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'datetime')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'julianday')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'unixepoch')
ctx.rule(u'SIMPLE_FUNC_NAME_T', u'strftime')
ctx.rule(u'PRAGMA_NAME_T', u'analysis_limit')
ctx.rule(u'PRAGMA_NAME_T', u'application_id')
ctx.rule(u'PRAGMA_NAME_T', u'auto_vacuum')
ctx.rule(u'PRAGMA_NAME_T', u'automatic_index')
ctx.rule(u'PRAGMA_NAME_T', u'busy_timeout')
ctx.rule(u'PRAGMA_NAME_T', u'cache_size')
ctx.rule(u'PRAGMA_NAME_T', u'cache_spill')
ctx.rule(u'PRAGMA_NAME_T', u'case_sensitive_like')
ctx.rule(u'PRAGMA_NAME_T', u'cell_size_check')
ctx.rule(u'PRAGMA_NAME_T', u'checkpoint_fullfsync')
ctx.rule(u'PRAGMA_NAME_T', u'collation_list')
ctx.rule(u'PRAGMA_NAME_T', u'compile_options')
ctx.rule(u'PRAGMA_NAME_T', u'data_version')
ctx.rule(u'PRAGMA_NAME_T', u'database_list')
ctx.rule(u'PRAGMA_NAME_T', u'defer_foreign_keys')
ctx.rule(u'PRAGMA_NAME_T', u'encoding')
ctx.rule(u'PRAGMA_NAME_T', u'foreign_key_check')
ctx.rule(u'PRAGMA_NAME_T', u'foreign_key_list')
ctx.rule(u'PRAGMA_NAME_T', u'foreign_keys')
ctx.rule(u'PRAGMA_NAME_T', u'freelist_count')
ctx.rule(u'PRAGMA_NAME_T', u'fullfsync')
ctx.rule(u'PRAGMA_NAME_T', u'function_list')
ctx.rule(u'PRAGMA_NAME_T', u'hard_heap_limit')
ctx.rule(u'PRAGMA_NAME_T', u'ignore_check_constraints')
ctx.rule(u'PRAGMA_NAME_T', u'incremental_vacuum')
ctx.rule(u'PRAGMA_NAME_T', u'index_info')
ctx.rule(u'PRAGMA_NAME_T', u'index_list')
ctx.rule(u'PRAGMA_NAME_T', u'index_xinfo')
ctx.rule(u'PRAGMA_NAME_T', u'integrity_check')
ctx.rule(u'PRAGMA_NAME_T', u'journal_mode')
ctx.rule(u'PRAGMA_NAME_T', u'journal_size_limit')
ctx.rule(u'PRAGMA_NAME_T', u'legacy_alter_table')
ctx.rule(u'PRAGMA_NAME_T', u'legacy_file_format')
ctx.rule(u'PRAGMA_NAME_T', u'locking_mode')
ctx.rule(u'PRAGMA_NAME_T', u'max_page_count')
ctx.rule(u'PRAGMA_NAME_T', u'mmap_size')
ctx.rule(u'PRAGMA_NAME_T', u'module_list')
ctx.rule(u'PRAGMA_NAME_T', u'optimize')
ctx.rule(u'PRAGMA_NAME_T', u'page_count')
ctx.rule(u'PRAGMA_NAME_T', u'page_size')
ctx.rule(u'PRAGMA_NAME_T', u'parser_trace')
ctx.rule(u'PRAGMA_NAME_T', u'pragma_list')
ctx.rule(u'PRAGMA_NAME_T', u'query_only')
ctx.rule(u'PRAGMA_NAME_T', u'quick_check')
ctx.rule(u'PRAGMA_NAME_T', u'read_uncommitted')
ctx.rule(u'PRAGMA_NAME_T', u'recursive_triggers')
ctx.rule(u'PRAGMA_NAME_T', u'reverse_unordered_selects')
ctx.rule(u'PRAGMA_NAME_T', u'schema_version')
ctx.rule(u'PRAGMA_NAME_T', u'secure_delete')
ctx.rule(u'PRAGMA_NAME_T', u'shrink_memory')
ctx.rule(u'PRAGMA_NAME_T', u'soft_heap_limit')
ctx.rule(u'PRAGMA_NAME_T', u'stats')
ctx.rule(u'PRAGMA_NAME_T', u'synchronous')
ctx.rule(u'PRAGMA_NAME_T', u'table_info')
ctx.rule(u'PRAGMA_NAME_T', u'table_list')
ctx.rule(u'PRAGMA_NAME_T', u'table_xinfo')
ctx.rule(u'PRAGMA_NAME_T', u'temp_store')
ctx.rule(u'PRAGMA_NAME_T', u'threads')
ctx.rule(u'PRAGMA_NAME_T', u'trusted_schema')
ctx.rule(u'PRAGMA_NAME_T', u'user_version')
ctx.rule(u'PRAGMA_NAME_T', u'vdbe_addoptrace')
ctx.rule(u'PRAGMA_NAME_T', u'vdbe_debug')
ctx.rule(u'PRAGMA_NAME_T', u'vdbe_listing')
ctx.rule(u'PRAGMA_NAME_T', u'vdbe_trace')
ctx.rule(u'PRAGMA_NAME_T', u'wal_autocheckpoint')
ctx.rule(u'AGGREGATE_FUNC_NAME_T', u'avg')
ctx.rule(u'AGGREGATE_FUNC_NAME_T', u'count')
ctx.rule(u'AGGREGATE_FUNC_NAME_T', u'group_concat')
ctx.rule(u'AGGREGATE_FUNC_NAME_T', u'sum')
ctx.rule(u'AGGREGATE_FUNC_NAME_T', u'total')
ctx.rule(u'COLUMN_NAME_T', u'c0')
ctx.rule(u'COLUMN_NAME_T', u'c1')
ctx.rule(u'COLUMN_NAME_T', u'NEW.c0')
ctx.rule(u'COLUMN_NAME_T', u'NEW.c1')
ctx.rule(u'COLUMN_NAME_T', u'OLD.c0')
ctx.rule(u'COLUMN_NAME_T', u'OLD.c1')
ctx.rule(u'COLUMN_NAME_T', u'name')
ctx.rule(u'COLUMN_NAME_T', u'path')
ctx.rule(u'COLUMN_NAME_T', u'pageno')
ctx.rule(u'COLUMN_NAME_T', u'pagetype')
ctx.rule(u'COLUMN_NAME_T', u'ncell')
ctx.rule(u'COLUMN_NAME_T', u'payload')
ctx.rule(u'COLUMN_NAME_T', u'unused')
ctx.rule(u'COLUMN_NAME_T', u'mx_payload')
ctx.rule(u'COLUMN_NAME_T', u'pgoffset')
ctx.rule(u'COLUMN_NAME_T', u'pgsize')
ctx.rule(u'COLUMN_NAME_T', u'type')
ctx.rule(u'COLUMN_NAME_T', u'tbl_name')
ctx.rule(u'COLUMN_NAME_T', u'rootpage')
ctx.rule(u'COLUMN_NAME_T', u'sql')
ctx.rule(u'TABLE_NAME_T', u't0')
ctx.rule(u'TABLE_NAME_T', u't1')
ctx.rule(u'TABLE_NAME_T', u't2')
ctx.rule(u'TABLE_NAME_T', u'sqlite_schema')
ctx.rule(u'TABLE_NAME_T', u'sqlite_temp_schema')
ctx.rule(u'TABLE_NAME_T', u'dbstat')
ctx.rule(u'INDEX_NAME_T', u'index0')
ctx.rule(u'INDEX_NAME_T', u'index1')
ctx.rule(u'TRIGGER_NAME_T', u'trig0')
ctx.rule(u'TRIGGER_NAME_T', u'trig1')
ctx.rule(u'VIEW_NAME_T', u'view0')
ctx.rule(u'VIEW_NAME_T', u'view1')
ctx.rule(u'SAVEPOINT_NAME_T', u'sav0')
ctx.rule(u'SAVEPOINT_NAME_T', u'sav1')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'row_number')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'rank')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'dense_rank')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'percent_rank')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'cume_dist')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'ntile')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'lag')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'lead')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'first_value')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'last_value')
ctx.rule(u'WINDOW_FUNC_NAME_T', u'nth_value')
ctx.rule(u'WINDOW_NAME_T', u'win0')
ctx.rule(u'WINDOW_NAME_T', u'win1')
ctx.rule(u'SCHEMA_NAME_T', u'main')
ctx.rule(u'SCHEMA_NAME_T', u'temp')
ctx.rule(u'ERROR_MESSAGE_T', u'\'ahh\'')
ctx.rule(u'TYPE_BASE_NAME_T', u'INTEGER')
ctx.rule(u'TYPE_BASE_NAME_T', u'REAL')
ctx.rule(u'TYPE_BASE_NAME_T', u'TEXT')
ctx.rule(u'TYPE_BASE_NAME_T', u'BLOB')
ctx.rule(u'CONSTRAINT_NAME_T', u'constr0')
ctx.rule(u'CONSTRAINT_NAME_T', u'constr1')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'UTF-8')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'UTF-16')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'UTF-16le')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'UTF-16be')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'TRUNCATE')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'PERSIST')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'MEMORY')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'WAL')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'OFF')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'NORMAL')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'FAST')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'PASSIVE')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'RESTAR_T')
ctx.rule(u'PRAGMA_SPECIAL_VALUE_T', u'RESET')
ctx.rule(u'NUMERIC_LITERAL_T', u'0.0')
ctx.rule(u'NUMERIC_LITERAL_T', u'0')
ctx.rule(u'NUMERIC_LITERAL_T', u'7')
ctx.rule(u'NUMERIC_LITERAL_T', u'3.14')
ctx.rule(u'NUMERIC_LITERAL_T', u'0xda')
ctx.rule(u'NUMERIC_LITERAL_T', u'42e-300')
ctx.rule(u'NUMERIC_LITERAL_T', u'5e200')
ctx.rule(u'NUMERIC_LITERAL_T', u'0xffff')
ctx.rule(u'STRING_LITERAL_T', u'\'lit0\'')
ctx.rule(u'STRING_LITERAL_T', u'\'\'')
ctx.rule(u'STRING_LITERAL_T', u'\':memory:\'')
ctx.rule(u'STRING_LITERAL_T', u'\'%Y-%m-%d\'')
ctx.rule(u'STRING_LITERAL_T', u'\'%H:%M:%S.%f\'')
ctx.rule(u'STRING_LITERAL_T', u'\'%J%j%w%s\'')
ctx.rule(u'STRING_LITERAL_T', u'\'%%\'')
ctx.rule(u'STRING_LITERAL_T', u'\'unixepoch\'')
ctx.rule(u'STRING_LITERAL_T', u'\'auto\'')
ctx.rule(u'BLOB_LITERAL_T', u'X\'53514C697465\'')
ctx.rule(u'NEWLINE_T', u'\n')

